### PR TITLE
Plugin API to handle analytics and custom plugins.

### PR DESCRIPTION
**Pull request by ascariandrea**
Hi,
I need to work with `ecommerce` module of analytics, so I added 2 methods to deal with plugins in general.

Can be helpful?

Thanks :)

### CODE REVIEW

**Comment by adamlofting** [comment]
Thanks for opening this PR @ascariandrea - I'll take a look at this soon and let you know if it's OK.

**Comment by ascariandrea** [comment]
@adamlofting Any updates?

**Comment by dmitry** [comment]
I would also see similar functionality in react-ga. I think docs in the readme file are missing, and commits could be rebased into a one or two commits.

**Comment by ascariandrea** [comment]
I'm going to take care of what you @dmitry said asap, thanks for the consideration :)

**Comment by dmitry** [comment]
@ascariandrea I would also make `require` function with `name` attribute, because could be that not only the `ecommerce` may be used (like I did it here: https://github.com/dmitry/react-ga/commit/36a31f9edad6832175835623e143cee859c386e6#diff-090b05cdc4c33b5b4d778c13de44d8eaR233)

**Comment by ascariandrea** [comment]
@dmitry I rebased master, added the `name` attribute for the `require` function, squashed commits and update the README.md. @adamlofting what do you think?

**Comment by dmitry** [comment]
@ascariandrea awesome! :+1: :rocket: Hopefully will be merged very soon.

**Comment by adamlofting** [comment]
@ascariandrea @dmitry sorry again for such a slow reply.

This is an *excellent* addition to the module. Thank you very much for taking the time and effort to write it.

@ascariandrea I'm not seeing the update you made with the `name` attribute in the `require` function, but I'm going to merge this now and will make that tweak as a follow up.

**Comment by dmitry** [comment]
Thanks for :shipit:

**Comment by ascariandrea** [comment]
Thanks @adamlofting , glad to be helpful!

**Pull request merged**
